name: Azure Continuous Delivery - Develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  ACR_NAME: felipepachon
  IMAGE_REPOSITORY: api-vise
  IMAGE_TAG: develop-${{ github.run_number }}
  AZURE_WEBAPP_NAME: visebank777-dev

  IMAGE_URL: felipepachon.azurecr.io/api-vise:develop-${{ github.run_number }}

jobs:
  build-and-push:
    name: Build and Push Docker image to Azure Container Registry (develop)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_URL }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_URL }}

      - name: Verify image pushed
        run: echo "✅ Image pushed: ${{ env.IMAGE_URL }}"

  deploy:
    name: Deploy to Azure Web App (Develop)
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_HARRIZON }}
          images: ${{ env.IMAGE_URL }}

      - name: Verify deployment
        run: |
          echo "🚀 Deployed develop branch to ${{ env.AZURE_WEBAPP_NAME }}"
          echo "🔗 URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
