name: Azure Continuous Delivery

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      IMAGE_REPOSITORY:
        description: 'Repository of the image (same as declared in App Service creation)'
        required: true
        default: 'api-vise'
      IMAGE_TAG:
        description: 'Tag of the image'
        required: true
        default: 'latest'
      AZURE_WEBAPP_NAME:
        description: 'Nombre del App Service creado en Azure'
        required: true
        default: 'visebank777'
      PORT:
        description: 'Port of the application'
        required: true
        default: '443'

env:
  ACR_NAME: felipepachon
  IMAGE_URL: felipepachon.azurecr.io/${{ github.event.inputs.IMAGE_REPOSITORY || 'api-vise' }}:${{ github.event.inputs.IMAGE_TAG || 'latest' }}

jobs:
  build-and-push:
    name: Build and Push Docker image to Azure Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_URL }} .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.IMAGE_URL }}

      - name: Verify image pushed
        run: echo "✅ Image pushed: ${{ env.IMAGE_URL }}"

  deploy:
    name: Deploy image to Azure Web App
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.event.inputs.AZURE_WEBAPP_NAME || 'visebank777' }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_HARRIZON }}
          images: ${{ env.IMAGE_URL }}

      - name: Verify deployment
        run: |
          echo "🚀 Deployment completed successfully for ${{ github.event.inputs.AZURE_WEBAPP_NAME || 'visebank777' }}"
          echo "URL: https://${{ github.event.inputs.AZURE_WEBAPP_NAME || 'visebank777' }}.azurewebsites.net"
