name: Azure Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      IMAGE_REPOSITORY:
        description: "Repository of the image (same as declared in App Service creation)"
        required: true
        default: "api-vise"
      IMAGE_TAG:
        description: "Tag of the image"
        required: true
        default: "latest"
      AZURE_WEBAPP_NAME:
        description: "Nombre del App Service creado en Azure"
        required: true
      PORT:
        description: "Port of the application"
        required: true
        default: "443"

env:
  # Nombre del servidor de login de ACR: <ACR_NAME>.azurecr.io
  ACR_LOGIN_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  # URL completa de la imagen que construiremos y usaremos para desplegar
  IMAGE_URL: ${{ secrets.ACR_NAME }}.azurecr.io/${{ inputs.IMAGE_REPOSITORY }}:${{ inputs.IMAGE_TAG }}

jobs:
  build-and-push-image:
    name: Build and Push to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push to ACR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_URL }}

  deploy:
    name: Deploy remote container to Azure
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FELIPEPACHON }}
          images: ${{ env.IMAGE_URL }}

  test-deploy:
    name: Test deployed service
    runs-on: ubuntu-latest
    needs: [build-and-push-image, deploy]

    steps:
      # 1️⃣ Instalar Hurl
      - name: Setup hurl (API testing tool)
        uses: gacts/install-hurl@v1

      # 2️⃣ Crear el archivo session.hurl
      - name: Create session.hurl
        run: |
          cat > session.hurl <<'HURL'
          # Crear cliente
          POST {{host}}/client
          Content-Type: application/json

          {
            "name": "Alice",
            "country": "USA",
            "monthlyIncome": 5000,
            "viseClub": true,
            "cardType": "Gold"
          }

          HTTP/1.1 201
          jsonpath "$.status" == "Registered"
          capture client_id jsonpath "$.clientId"

          # Realizar compra
          POST {{host}}/purchase
          Content-Type: application/json

          {
            "clientId": {{client_id}},
            "amount": 100,
            "currency": "USD",
            "purchaseDate": "2025-01-01",
            "purchaseCountry": "USA"
          }

          HTTP/1.1 200
          jsonpath "$.status" == "Approved"
          HURL

      # 3️⃣ Mostrar el archivo (para debug)
      - name: Show session.hurl (with line numbers)
        run: nl -ba session.hurl

      # 4️⃣ Ejecutar pruebas con Hurl
      - name: Test API
        run: |
          hurl \
            --variable host="https://${{ inputs.AZURE_WEBAPP_NAME }}.azurewebsites.net:${{ inputs.PORT }}" \
            --connect-timeout 20s \
            --error-format long \
            --verbose \
            --test session.hurl
